# 배열의 형태(shape) 변경-> 오늘한 건 다 기억!

## reshape()을 이용한 차원 변경 : 원하는 형태로 지정해서 바꿈
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.

In [1]:
import numpy as np

In [2]:
a = np.arange(20)
print(a.shape)
print(a.size)
a


(20,)
20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
b = np.reshape(a,(4,5))
print(b.shape)
print(b.size)
b

(4, 5)
20


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [4]:
c = a.reshape(4,5)
print(c.shape)
print(c.size)
print(c)

(4, 5)
20
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
c1 = a.reshape((4,5))
print(c1.shape)
print(c1)

(4, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [6]:
e = a.reshape(2,2,5)
print(e.size)
print(e.shape)
print(e)

20
(2, 2, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [8]:
f= np.arange(125).reshape(5,5,5)
f

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [9]:
f = np.arange(5*5*5).reshape(5,5,5)
g = np.arange(3*2*7).reshape(3*2*7)

In [10]:
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41])

In [12]:
f_1= np.reshape(f, 125) #뉴쉐입자리에 정수대입 : 1차원배열로
print(f_1.shape)
f_1

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [13]:
f_2 = np.reshape(f, -1)
print(f_2.shape)
f_2

(125,)


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

In [14]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:

f_1 = np.reshape(a,(5,-1))
print(f_1.shape)

(5, 4)


In [17]:
a_2 = a.reshape(2,2,-1)
print(a_2.shape)

(2, 2, 5)


In [18]:
a = np.arange(20)
print(a.shape)
print(a.size)
a

(20,)
20


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## 차원 늘리기(확장)

### numpy.newaxis 속성을 이용해 차원 늘리기 : 사이즈가 1인 차원을 늘린다
- size가 1인 축을 늘릴때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.

In [20]:
a = np.arange(1,6)
print(a.shape)
print(a)

(5,)
[1 2 3 4 5]


In [21]:
a[:]# 그대로 유지하려는 축은 전체조회하는 슬라이싱을 하고, 축을 늘리려는 쪽에다가 np.newaxis 
x = a[np.newaxis, :] #o번축 늘림
print(x.shape)
x

(1, 5)


array([[1, 2, 3, 4, 5]])

In [22]:
y = a[ : ,np.newaxis]
print(y)
print(y.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [23]:
z = a[np.newaxis, : , np.newaxis]
print(z.shape)

(1, 5, 1)


In [24]:
b = np.arange(6).reshape(2,3)
print(b.shape)
b

(2, 3)


array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
m = b[np.newaxis, :,:]
print(m.shape)
print(m)

(1, 2, 3)
[[[0 1 2]
  [3 4 5]]]


In [26]:
o = b[:,np.newaxis,:,np.newaxis]
print(o.shape)
print(o)

(2, 1, 3, 1)
[[[[0]
   [1]
   [2]]]


 [[[3]
   [4]
   [5]]]]


In [27]:
### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능
- 내가 쓸 함수는 3차원배열인데, 내가가진 데이터가 2차원일 때 이런걸 사용해서 늘려서 함수에 대입

SyntaxError: invalid syntax (<ipython-input-27-642c8844c1bf>, line 3)

In [28]:
#(2,3,4)->(1,2,3,4) : 앞에다가 축을 하나 늘리고 싶은데 뒤는 원래있던거 그대로 넣어
# 원래값이 들어올 자리에 ...으로 표시하는 것


In [29]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
b2 = b[np.newaxis, ...]
print(b2.shape)

(1, 2, 3)


In [33]:
b3 = b[...,np.newaxis]
print(b3.shape)
print(b3)

(2, 3, 1)
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]


In [34]:
b4= np.reshape(b,(2,3,1))

In [35]:
b4

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [36]:

print(b4.shape)

(2, 3, 1)


### numpy.expand_dims (배열, axis)  : 사이즈가 1인 차원을 늘린다
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.
- 첫번째 방식의 함수버전

In [37]:
print(a.shape)
a

(5,)


array([1, 2, 3, 4, 5])

In [38]:
a1 = np.expand_dims(a, axis = 1)
print(a1.shape)
a1

(5, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [39]:
a2= np.expand_dims(a,axis =0)
a2.shape

(1, 5)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [41]:
a = np.arange(12).reshape(1,2,1,2,3,1)

In [42]:
a.shape

(1, 2, 1, 2, 3, 1)

In [43]:
b = np.squeeze(a)
b.shape

(2, 2, 3)

In [44]:
b1 = np.squeeze(a, axis = 2)
b1.shape

(1, 2, 2, 3, 1)

In [45]:
b1 = np.squeeze(a, axis = 1)

ValueError: cannot select an axis to squeeze out which has size not equal to one

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.(무조건 1차원으로!)

In [47]:
a = np.arange(20).reshape(2,2,5)
a.shape

(2, 2, 5)

In [48]:
a2 = a.flatten()
a2.shape

(20,)

In [49]:
flatten(a)

NameError: name 'flatten' is not defined

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.(1가지 축으로 만든다음 삽입)
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

In [50]:
#append

In [51]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [53]:
r = np.append(a,100)
r

array([  1,   2,   3, 100])

In [54]:
r = np.append(a,[200,300,400])
r


array([  1,   2,   3, 200, 300, 400])

In [55]:
l = [
    [1,1],
    [2,2],
    [3,3]
]
b = np.array(l)
print(b.shape)
b

(3, 2)


array([[1, 1],
       [2, 2],
       [3, 3]])

In [56]:
r = np.append(b,[[4,4]], axis = 0)
r

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [58]:
r = np.append([[4,4],[5,5],[6,6]], axis= 0)
r


TypeError: _append_dispatcher() missing 1 required positional argument: 'values'

In [91]:
b = np.arange(36).reshape(6,6)
b.shape

(6, 6)

In [93]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [94]:
np.delete(b,[0,1],axis = 0)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [95]:
np.delete(b,[0,1],axis = 1)

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29],
       [32, 33, 34, 35]])

In [96]:
np.delete(b,0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35])

In [97]:
k = np.arange(12).reshape(2,2,3)
k

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [99]:
np.append(k,[[[1,1,1]],[[2,2,2]]],axis = 1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 1,  1,  1]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 2,  2,  2]]])

## 배열 합치기 : 데이터가 너무 많아?-> 차원과 합치려는 기준 컬럼을 제외한 나머지 컬럼의 사이즈가 동일해야.
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다. 예)2차원은 2차원끼리 합쳐/
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.(기준이 되는 축은 늘어나는데, 기준축 이외의 것은 동일하다)
        - 예) (3,5) + (3,5)axis = 1 일때 (3, 10)이 됨
        - 같은 축의 데이터 갯수는 같아야. 합쳤을 때 비어버리니까 안돼.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

a:(3,2), b:(3,5)  : axis = 1( 3,7)  
a:(4,2), b:(4,2) : axis = 0 (8,2), axis = 1 (4,4)  
a:(2,3,5), b:(3,1,5) : 안돼. 최소 2개 같아야돼 (3차원일때)  
a:(2,3,5),b(7,3,5), axis = 0 (9,3,5)
    

axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)  
그래서 각 배열의 컬럼 수가 같아야 한다.  
axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)  
그래서 각 배열의 행수가 같아야 한다.m  

In [101]:
import numpy as np
a = np.array([1,2,3])
b = np.array([10,20,30,40])
c = np.array([100,200])
#1차원 배열 합쳐
e = np.concatenate([b,a])
e

array([10, 20, 30, 40,  1,  2,  3])

In [102]:
np.concatenate([a,b,c])

array([  1,   2,   3,  10,  20,  30,  40, 100, 200])

In [103]:
x = np.arange(6).reshape(2,3)
y = np.arange(10,16).reshape(2,3)
z = np.arange(20,26).reshape(2,3)
print(x.shape, y.shape, z.shape)

(2, 3) (2, 3) (2, 3)


In [104]:
r= np.concatenate([x,y],axis = 0)
print(r.shape)
print(r)

(4, 3)
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]]


In [106]:
r = np.concatenate([x,y],axis = 1)
print(r.shape)
print(r)

(2, 6)
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]]


In [108]:
r = np.concatenate([x,y,z],axis = 0)
print(r.shape)
print(r)

(6, 3)
[[ 0  1  2]
 [ 3  4  5]
 [10 11 12]
 [13 14 15]
 [20 21 22]
 [23 24 25]]


In [109]:
r = np.concatenate([x,y,z],axis = 1)
print(r.shape)
print(r)


(2, 9)
[[ 0  1  2 10 11 12 20 21 22]
 [ 3  4  5 13 14 15 23 24 25]]


In [110]:
w = np.arange(10).reshape(2,5)
w.shape

(2, 5)

In [111]:
np.concatenate([x,w],axis = 1)


array([[0, 1, 2, 0, 1, 2, 3, 4],
       [3, 4, 5, 5, 6, 7, 8, 9]])

In [112]:
r = np.concatenate([x,w],axis = 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

In [113]:
#vstack(아래에 붙임)

In [114]:
x.shape, y.shape, z.shape

((2, 3), (2, 3), (2, 3))

In [116]:
np.vstack([x,y])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [117]:
np.vstack([x,y,z])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [20, 21, 22],
       [23, 24, 25]])

In [118]:
w.shape

(2, 5)

In [119]:
np.vstack([x,w])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.(수평으로)
- axis=1과 동일

In [120]:
np.hstack([x,y,z])

array([[ 0,  1,  2, 10, 11, 12, 20, 21, 22],
       [ 3,  4,  5, 13, 14, 15, 23, 24, 25]])

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준 : 분할기준 주는 방법 2가지
        - 정수 : 지정 개수만큼 분할 예) 나눴을때 나온 사이즈들이 각 동일해야 나눌 수 있음.
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
    - 2차원 배열 편하게 하기위한게 아래 두가지
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

In [121]:
import numpy as np
a=np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
r = np.split(a, 2)
print(r)
print(type(r))

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
<class 'list'>


In [124]:
r=np.split(a,3)

ValueError: array split does not result in an equal division

In [125]:
r = np.split(a,[2,6])
r

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]

In [126]:
r = np.split(a,[4])

In [127]:
r

[array([0, 1, 2, 3]), array([4, 5, 6, 7, 8, 9])]

In [128]:
b = np.arange(16).reshape(4,4)
print(b.shape)
b

(4, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [129]:
np.split(b,2,axis = 0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [130]:
r = np.split(b,2,axis = 1)

In [131]:
r

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [132]:
np.split(b,[1,3],axis = 0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [133]:
c = np.arange(6*6*8).reshape(6,6,8)
c.shape

(6, 6, 8)

In [134]:
r = np.split(c,2,axis = 0)
print(r[0].shape, r[1].shape) # 쪼개지는 기준 축의 갯수만 줄어

(3, 6, 8) (3, 6, 8)


## hsplit()/vsplit()

In [136]:
c = np.arange(64).reshape(8,8)
c.shape

(8, 8)

In [137]:
r = np.vsplit(c,4)

In [140]:
print(r)
print(r[0].shape)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]]), array([[32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]]), array([[48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
(2, 8)


In [141]:
r = np.vsplit(c,[3,6])
print(r[0].shape,r[1].shape, r[2].shape)

(3, 8) (3, 8) (2, 8)


In [142]:
np.hsplit(c,5)

ValueError: array split does not result in an equal division